<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\WebtreesApi;

use DateTimeImmutable;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Site;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Webtrees;
use Jefferson49\Webtrees\Helpers\ClassName;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\CreateKeysModal;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\CreateTokenModal;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\DeleteClient;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\EditClientAction;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\EditClientModal;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\RevokeToken;
use Jefferson49\Webtrees\Module\WebtreesApi\Http\RequestHandlers\TestApi;
use Jefferson49\Webtrees\Module\WebtreesApi\OAuth2\Repositories\AccessTokenRepository;

use function e;


/**
 * @var string $title
 * @var bool   $pretty_urls
 * @var string $webtrees_api_token
 * @var string $webtrees_api_url
 * @var string $pretty_webtrees_api_url
 * @var string $mcp_url
 * @var string $pretty_mcp_url
 * @var string $access_token_url
 * @var string $pretty_access_token_url
 * @var array  $user_list
 * @var int    $swagger_user
 * @var array  $clients
 * @var array  $client_identifiers
 * @var array  $access_tokens
 * @var array  $scope_identifiers
 * @var AccessTokenRepository $access_token_repository
 * @var string $encryption_key
 * @var string $path_for_keys
 * @var string $public_key_path
 * @var string $private_key_path
 * @var string $error_message
 * @var bool   $allow_mcp_read_member
 * @var bool   $debugging_activated
*/

$data_folder = str_replace('\\', '/', Registry::filesystem()->dataName());
$root_folder = str_replace('\\', '/', Registry::filesystem()->rootName());
$data_folder_relative = str_replace($root_folder, '', $data_folder);

// Class for data tables
if (version_compare(Webtrees::VERSION, '2.3', '>=')) {
    $data_tables_class = "wt-datatables";
} else {
    $data_tables_class = "datatables";
}

?>

<?= view('components/breadcrumbs', ['links' => [route(ClassName::get(ClassName::CONTROL_PANEL)) => I18N::translate('Control panel'), e($title)]]) ?>

<h1><?=e($title) ?></h1>
<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" id="settings-form">
	<input type="hidden" name="save" id="save" value="1">

	<div class="h4">
		<?= I18N::translate('OAuth2 Server Settings') ?>
	</div>

	<div class="row mb-3">
		<?php if ($error_message !== '') : ?>
			<div class="alert alert-danger">
				<?= e($error_message) ?>
			</div>
		<?php endif ?>
	</div>

	<div class="row mb-3">
		<?php if (!$uses_https) : ?>
			<div class="alert alert-warning">
				<?= I18N::translate('Currently, webtrees does not use the HTTPS protocol. It is highly recommended to use HTTPS in order to ensure the encryption of access tokens within API requests. HTTPS can be activated by changing "base_url" in the "config.ini.php". Currently, "base_url" does not start with "https://".') ?>
			</div>
		<?php endif ?>
	</div>

	<div class="row">
		<div class="row mb-3">
			<?php if (substr_compare($path_for_keys, $data_folder, 0, strlen($data_folder)) !== 0) : ?>
				<div class="alert alert-danger">
					<p>
						<?= I18N::translate('Currently, the path for the private/public keys is not a sub-directory of the webtrees data folder. If the keys path lies within the webtrees installation, it is highly recommended to use the webtrees data folder or a sub-directory, because webtrees protects unauthorized access to this folder. If you choose a folder outside of the webtrees data folder, the keys might be unprotected against unauthorized access.' ) ?>
					</p>
				</div>
			<?php endif ?>
			<label class="col-sm-3 col-form-label wt-page-options-label" for="folder_to_save">
				<?= I18N::translate('Path for private/public keys') ?>
			</label>
			<div class="col-sm-9 wt-page-options-value">
				<input class="form-control" type="text" id="path_for_keys" name="path_for_keys" required="required" value="<?= e($path_for_keys) ?>">
			</div>
			<div class="form-text col-sm-9 offset-sm-3">
				<?= I18N::translate('Path to the private/public keys. If a path is used within the webtrees installation, it is highly recommended to use a path within the webtrees data folder, because webtrees protects unauthorized access to the data folder. The current settings (Control panel / Website preferences) for the webtrees root and data folder are:'); ?>
				<br>
				<b><?= I18N::translate('webtrees root folder') ?>: </b>
				<?= Registry::filesystem()->rootName() ?>
				<br>
				<b><?= I18N::translate('webtrees data folder') ?>: </b>
				<?= Registry::filesystem()->dataName() ?>
				<br>
				<b><?= I18N::translate('webtrees data folder (relative path)') ?>: </b>
				<?= e($data_folder_relative) ?>
				<br>
				<b><?= I18N::translate('webtrees data folder (setting in the control panel)') ?>: </b>
				<?= Site::getPreference('INDEX_DIRECTORY') ?>
				<br>
				<br>
				<b><?= I18N::translate('Private key')?>: </b>
				<?= e($private_key_path) ?>
				<br>
				<b><?= I18N::translate(message: 'Public key')?>: </b>
				<?= e($public_key_path) ?>
			</div>
			<div class="form-text col-sm-9 offset-sm-3">
				<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
						data-wt-href="<?= e(route(CreateKeysModal::class)) ?>">
					<input class="btn btn-secondary" type="submit" value="<?= I18N::translate('Create new keys') ?>">
				</a>
			</div>
		</div>
	</div>

	<div class="row mb-3">
		<label class="col-form-label col-sm-3" for="swagger_user">
			<?= I18N::translate('Technical user for API test') ?>
		</label>
		<div class="col-sm-9">
			<div class="input-group" required="required">
				<?= view('components/select', [
						'name'     => 'swagger_user',
						'id'       => 'swagger_user',
						'selected' => $swagger_user,
						'options'  => $user_list,
					])
				?>
			</div>
		</div>
		<div class="form-text col-sm-9 offset-sm-3">
			<?= I18N::translate('With the selected technical user, the access rights to trees in webtrees are specified within API calls. For a detailed description of technical users, please refer to the related chapter below.'); ?>
		</div>
	</div>

	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Local LLMs: Allow MCP scope mcp_read_member') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => MoreI18N::xlate('Allow'), 'name' => WebtreesApi::PREF_ALLOW_MCP_READ_MEMBER, 'checked' => $allow_mcp_read_member]) ?>
				<div class="form-text">
					<?= I18N::translate('If activated, the usage of the scope "mcp_read_member" will be allowed. It is highly recommended to activate for local LLMs only, because LLMs will get MCP read access without applying strict privacy rules.', e($title)); ?>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset class="mb-3">
		<div class="row">
			<legend class="col-form-label col-sm-3">
				<?= I18N::translate('Server logs') ?>
			</legend>
			<div class="col-sm-9">
				<?= view('components/checkbox', ['label' => MoreI18N::xlate('Activate'), 'name' => WebtreesApi::PREF_DEBUGGING_ACTIVATED, 'checked' => $debugging_activated]) ?>
				<div class="form-text">
					<?= I18N::translate('If selecting this option, additional debug information will be logged in the webtrees website logs.'); ?>
				</div>
			</div>
		</div>
	</fieldset>
	<div class="row mb-3">
		<?php if ($allow_mcp_read_member) : ?>
			<div class="alert alert-danger">
				<?= I18N::translate('Currently, the scope "mcp_read_member" is activated. Please make sure that "mcp_read_member" is only used for local LLMs, because LLMs will get MCP read access without applying strict privacy rules (e.g to protect the data of living persons).'); ?>
			</div>
		<?php endif ?>
	</div>

	<button type="submit" class="btn btn-primary">
		<?= MoreI18N::xlate('Save') ?>
	</button>
	<?= csrf_field() ?>
</form>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('webtrees API URL') ?>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= MoreI18N::xlate('URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($webtrees_api_url) ?></span>
	</div>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_webtrees_api_url) ?></span>
	</div>
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('MCP URL') ?>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= MoreI18N::xlate('URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($mcp_url) ?></span>
	</div>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_mcp_url) ?></span>
	</div>
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('OAuth2 Access Token URL') ?>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Access Token URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($access_token_url) ?></span>
	</div>
</div>
<div class="row">
	<label class="col-sm-3 col-form-label wt-page-options-label">
		<?= I18N::translate('Pretty URL') ?>
	</label>
	<div class="col-sm-9 wt-page-options-value">
		<span class="input-group-text"><?= e($pretty_access_token_url) ?></span>
	</div>
</div>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<form method="post" action="<?= e(route(TestApi::class)) ?>" id="test-api-form">
	<div class="h4">
		<?= I18N::translate('API Test with Swagger UI') ?>
	</div>
	<?php if ($pretty_urls) : ?>
		<div class="col">
			<button type="submit" class="btn btn-primary">
				<?= I18N::translate('Test webtrees API') ?>
			</button>
		</div>
	<?php else : ?>
		<div class="row mb-3">
			<div class="alert alert-warning">
				<?= I18N::translate('The API can only be tested with "pretty" URLs enabled. Check the <a href="https://webtrees.net/faq/urls/" target="_blank">webtrees documentation</a> about how to enable "pretty" URLs.') ?>
			</div>
		</div>
	<?php endif	?>
	<?= csrf_field() ?>
</form>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('Client Credentials') ?>
</div>

<table
	class="table table-bordered table-sm wt-table-module-updates <?= $data_tables_class ?> d-none"
	<?= view('lists/datatables-attributes') ?>
	data-columns="<?= e(json_encode([
		null,
		null,
		null,
		null,
		null,
		['type' => 'html', 'searchable' => false],
		['type' => 'html', 'searchable' => false],
		['type' => 'html', 'searchable' => false],
	], JSON_THROW_ON_ERROR)) ?>"
>
	<caption class="visually-hidden">
		<?= $caption ?? I18N::translate('Client Credentials') ?>
	</caption>
	<thead>
		<tr>
			<th><?= I18N::translate('Client Identifier') ?></th>
			<th><?= I18N::translate('Client Secret') ?></th>
			<th><?= I18N::translate('Client Name') ?></th>
			<th><?= I18N::translate('Scopes') ?></th>
			<th><?= I18N::translate('Technical User') ?></th>
			<th><?= MoreI18N::xlate('Edit') ?></th>
			<th><?= MoreI18N::xlate('Delete') ?></th>
			<th><?= I18N::translate('Create Access Token') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($clients as $client) : ?>
			<tr>
				<!-- Client Identifier -->
				<td data-sort="<?= e($client->getIdentifier()) ?>">
					<?= e($client->getIdentifier()) ?>
				</td>
				<!-- Client Secret -->
				<td>
					<?= '****' ?>
				</td>
				<!-- Client Name -->
				<td data-sort="<?= e($client->getName()) ?>">
					<?= e($client->getName()) ?>
				</td>
				<!-- Scopes -->
				<?php $client_scopes = array_map(fn($scope) => $scope->getIdentifier(), $client->getScopes()) ?>
				<td>
					<?= e(implode(' ', $client_scopes)) ?>
				</td>
				<!-- Technical User -->
				<td data-sort="<?= e($user_list[$client->getTechnicalUserId()] ?? '') ?>">
					<?= e($user_list[$client->getTechnicalUserId()] ?? '') ?>
				</td>
				<!-- Edit -->
				<td data-sort="<?= '' ?>">
					<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
							data-wt-href="<?= e(route(EditClientModal::class, [
								'edit_client_action' => EditClientAction::EDIT_CLIENT_ACTION_EDIT,
								'client_identifier'  => $client->getIdentifier(),
								'client_secret_hash' => $client->getClientSecretHash(),
								'client_name'        => $client->getName(),
								'scope_identifiers'  => $scope_identifiers,
								'client_scopes'      => $client_scopes,
								'user_list'          => $user_list,
								'technical_user_id'  => $client->getTechnicalUserId(),
							]
						)) ?>">
						<input class="btn btn-primary" type="submit" value="<?= MoreI18N::xlate('Edit') ?>">
					</a>
				</td>
				<!-- Delete -->
				<?php $client_has_tokens = !empty($access_token_repository->accessTokensForClient($client->getIdentifier())) ?>
				<td>
					<?php if (!$client_has_tokens) : ?>
						<a href="<?= e(route(DeleteClient::class, [
									'client_identifier' => $client->getIdentifier(),
								]
								)) ?>" type="submit" class="btn btn-primary">
							<?= MoreI18N::xlate('Delete') ?>
						</a>
					<?php else : ?>
						<?= I18N::translate('Client has tokens assigned') ?>
					<?php endif ?>
				</td>
				<!-- Create Access Token -->
				<td>
					<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
							data-wt-href="<?= e(route(CreateTokenModal::class, [
								'client_identifier'    => $client->getIdentifier(),
								'scope_identifiers'    => $client_scopes,
								'token_scopes'         => $client_scopes,
								'expiration_intervals' => AccessTokenRepository::getExpirationIntervals(),
								'expiration_interval'  => AccessTokenRepository::DEFAULT_EXPIRATION_INTERVAL,
							]
						)) ?>">
						<input class="btn btn-primary" type="submit" value="<?= I18N::translate('Create access token') ?>">
					</a>
				</td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
<a href="#" data-bs-toggle="modal" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal"
		data-wt-href="<?= e(route(EditClientModal::class, [
			'edit_client_action' => EditClientAction::EDIT_CLIENT_ACTION_ADD,
			'scope_identifiers'  => $scope_identifiers,
			'client_scopes'      => [],
			'user_list'          => $user_list,
		]
	)) ?>">
	<input class="btn btn-primary" type="submit" value="<?= I18N::translate('Add client') ?>">
</a>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('Access Tokens') ?>
</div>
<p><?= I18N::translate('Currently, the following access tokens are active, i.e. not expired yet.') ?></p>
<table
	class="table table-bordered table-sm wt-table-module-updates <?= $data_tables_class ?> d-none"
	<?= view('lists/datatables-attributes') ?>
	data-columns="<?= e(json_encode([
		null,
		null,
		null,
		null,
		null,
		null,
		['type' => 'html', 'searchable' => false],
	], JSON_THROW_ON_ERROR)) ?>"
>
	<caption class="visually-hidden">
		<?= $caption ?? I18N::translate('Access Tokens') ?>
	</caption>

	<thead>
		<tr>
			<th><?= I18N::translate('Access Token') ?></th>
			<th><?= I18N::translate('Client Identifier') ?></th>
			<th><?= I18N::translate('Scopes') ?></th>
			<th><?= I18N::translate('Expiration Date') ?></th>
			<th><?= I18N::translate(message: 'Created with') ?></th>
			<th><?= I18N::translate('Revoked') ?></th>
			<th><?= I18N::translate('Revoke') ?></th>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($access_tokens as $token) : ?>
			<tr>
				<!-- Access Token -->
				<td data-sort="<?= e($token->getShortToken()) ?>">
					<?= e('****' . $token->getShortToken()) ?>
				</td>
				<!-- Client Identifier -->
				<td data-sort="<?= e($token->getClient()->getIdentifier()) ?>">
					<?= e($token->getClient()->getIdentifier()) ?>
				</td>
				<!-- Scopes -->
				<?php $token_scopes = array_map(fn($scope) => $scope->getIdentifier(), $token->getScopes()) ?>
				<td>
					<?= e(implode(' ', $token_scopes)) ?>
				</td>
				<!-- Expiration Date -->
				<td data-sort="<?= e($token->getExpiryDateTime()->format(DateTimeImmutable::ATOM)) ?>">
					<?= e($token->getExpiryDateTime()->format(DateTimeImmutable::ATOM)) ?>
				</td>
				<!-- Created with -->
				<td data-sort="<?= e($token->wasCreatedInControlPanel() ? I18N::translate('Added in the module settings') : I18N::translate('Token request using client credentials')) ?>">
					<?= e($token->wasCreatedInControlPanel() ? I18N::translate('Added in the module settings') : I18N::translate('Token request using client credentials')) ?>				</td>
				<!-- Revoked -->
				<td data-sort="<?= e($token->isRevoked() ? MoreI18N::xlate('yes') : MoreI18N::xlate('no')) ?>">
					<?= e($token->isRevoked()  ? MoreI18N::xlate('yes') : MoreI18N::xlate('no')) ?>
				</td>
				<!-- Revoke -->
				<td>
					<?php if (!$token->isRevoked()) : ?>
						<a href="<?= e(route(RevokeToken::class, [
									'token_identifier' => $token->getIdentifier(),
								]
								)) ?>" type="submit" class="btn btn-primary">
							<?= I18N::translate('Revoke') ?>
						</a>
					<?php endif ?>
				</td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>

<div class="row mb-3"><?= view('icons/spacer') ?></div>

<div class="h4">
	<?= I18N::translate('Explanation of Technical Users (to define API/MCP access rights)') ?>
</div>
<p><?= I18N::translate('By selecting a (technical) user, the access rights for API/MCP requests can be specified. Any tree data requested with API/MCP is limited to the access rights of the specified (technical) user.') ?></p>
<p><?= I18N::translate('It is recommended to create a separate (technical) user, which is only used to define the API/MCP access rights. The maximum access role, wich is allowed for the (technical) user is limited to an "Editor". "Moderators" or "Administrators" are denied access during API/MCP requests.') ?></p>
<p><?= I18N::translate('If new records etc. are created with API/MCP, the data is created with the specified (technical) user. In order to have control about the changed data, it is not allowed that the selected (technical) user has "Automatically accept changes" activated. This ensures that a moderator can always reject unintended changes during a review of pending changes.') ?></p>

<?php View::push('javascript') ?>
<script>
	document.body.addEventListener('hidden.bs.modal', function () {
		location.reload();
	});
</script>
<?php View::endpush() ?>
<?= view('modals/ajax') ?>
